apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: python-function
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: python-function
    apps.tanzu.vmware.com/has-tests: "no"
spec:
  source:
    git:
      url: https://github.com/fklein82/semantic-text-search-accelerator.git
      ref:
        branch: main
  build:
    env:
      - name: BP_FUNCTION
        value: func.main
